apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: fe-container
        image: gcr.io/mineral-minutia-820/grpc_backend
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /_ah/health
            port: 8081
            scheme: HTTPS
        readinessProbe:
          httpGet:
            path: /_ah/health
            scheme: HTTPS
            port: 8081           
        ports:
        - containerPort: 50051
          protocol: TCP
        - containerPort: 8081
          protocol: TCP                  
        command: ["/grpc_server"]
        args: ["--grpcport", ":50051", "--httpport", ":8081"]